### ISSUE TITLE
Utilize limit switches on the arm.

### ISSUE THREAD

**Issue by a2aaron** [FRC1076/FRC1076-2016-Competition#48]
The arm will have limit switches soon. We should use them.

When not pressed, the limit switch can either have a closed or open circuit (this can be chosen). When it is pressed, the opposite will occur. Make sure that the code can handle both cases if we want to change part way through.

**Comment by porglezomp** [comment]
I think you always want to use normally closed, that way if the limit switch fails, it fires instead of not responding.

**Comment by porglezomp** [comment]
I just realized, the limit switches should probably be resolved in hardware instead of software. We don't want to introduce extra delay, and we don't want some potential bug in our handling of it to damage the robot. The limit switches can be wired directly into the motor controllers and configured to stop them.

**Comment by a2aaron** [comment]
Today mechanical/electrical is wiring the limit switches, so we can do that instead. Electrical and mechanical both said that leaving the circuit open normally means that if the limit switch breaks somehow then we can still use the arm (we just have to be careful).

**Comment by porglezomp** [comment]
Are you able to change the open/closed behavior from software? If so, then it'd be nice to be normally closed during autonomous, so that auto mode can't break the robot, and then possibly make it normally open during teleop, if they want to have manual control over whether they break the robot.

I find it hard to argue that when something fails, the better behavior is that the robot is able to break itself instead of just being unable to move its arm.

**Comment by a2aaron** [comment]
In Teleop, the idea is that the drivers will still be able to use the arm carefully without damaging anything. It's better to use the arm unsafely than to lose all of the arm functionality during the middle of the match.

According to the [Talon SRX Software Reference](http://www.ctr-electronics.com/Talon%20SRX%20Software%20Reference%20Manual.pdf), it is possible to change between normally open and normally closed (page 40). However, there is a small time where the motor is disabled while switching. That seems to make it possible to switch between the end of autonomous and start of teleop.

**Comment by porglezomp** [comment]
Yeah, I'm mostly concerned about autonomous. While you're in autonomous, there is a legitimately high risk of damaging the robot if something goes wrong with the limit switch, and that damage is worse that missing part of a match. Switching at the end of autonomous is the minimum that I'd accept as responsible software.

**Comment by a2aaron** [comment]
It also seems that a "soft limit" exists (without a delay), which might be better for switching during autonomous and teleop, but it doesn't use an actual limit switch. It does rely on an encoder though

Once I get access to the robot I will test both methods and see which one works better.

**Comment by a2aaron** [comment]
Ok. I've created two possible versions. One uses limit switches (PR #52) and one uses limit switches _and_ soft limits (PR #51).

I also have a third version which simply leaves the limit switches in the normally open state.

**Comment by porglezomp** [comment]
Lots of good alternatives here!

**Comment by a2aaron** [comment]
#57 Decided to have the limit switches to be normally open because it was requested to be that way.
